require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test" << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

namespace :test do
  desc "Build the Rails test application in tmp (force=1 to rebuild)"
  task :app do
    require_relative "test/prepare_testapp"
    TestApp.build(:force => !ENV["force"].nil?)
  end
end

task :default => :test

# The pre-2026 suites are kept, not run: test/doctest (rubydoctest) and
# test/irt (irt, abandoned in 2015) are ported piece by piece as layer 4
# advances. See PLAN.md.
