require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test" << "lib" << "../hobo_support/lib" << "../hobo_fields/lib" << "../dryml/lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

task :default => :test

# The pre-2026 suites are kept, not run: test/doctest (rubydoctest) and
# test/irt (irt, abandoned in 2015) are ported piece by piece as layer 4
# advances. See PLAN.md.
