require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test" << "lib" << "../hobo_support/lib" << "../dryml/lib" << "../hobo_rapid/lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

task :default => :test
