require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test" << "lib" << "../hobo_support/lib" << "../hobo_fields/lib" << "../dryml/lib" << "../hobo/lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

task :default => :test

# The browser tests under test/browser need a headless Firefox and the Stimulus
# runtime; `cd hobo && rake test:app` puts both in place. Without them they skip
# and say so.
