require_relative 'hobo_helper_base'

module HoboPermissionsHelper
  extend HoboHelperBase
  protected

    # Who is asking. **An application that already answers this keeps its own
    # answer**, and that is not politeness: this module is included into every
    # controller that takes Hobo's pages, and its `app/helpers` is on the path
    # of every application that installs the gem, so this method lands on top of
    # whatever was there.
    #
    # What was there, in a real application, was Devise's -- and Hobo's answer
    # for somebody not logged in is a `Hobo::Model::Guest`, which has no email,
    # no name and no id. Adding the gem to an existing Rails 8 application broke
    # **every page of it**, starting with the layout: `current_user.email` on a
    # Guest. The application had not asked Hobo for anything yet.
    #
    # `defined?(super)` is the whole fix: if anybody up the chain answers this,
    # they are the authority.
    def current_user
      return super if defined?(super)
      # simple one-hit-per-request cache
      @current_user ||= rails_authenticated_user || hobo_session_user || guest_user
    end

    # Rails 8's authentication generator does not define `current_user`: it puts
    # the session on `Current`, and asks `authenticated?`. Hobo has always had
    # its own `current_user`, and until these two were introduced they never
    # met -- a person could log in and Hobo still saw a guest, so every form
    # came out read-only and no action was ever offered.
    #
    # Piece 15 delegates the user to Rails, and this is the seam.
    def rails_authenticated_user
      return nil unless defined?(::Current)
      ::Current.try(:user) || ::Current.try(:session)&.try(:user)
    rescue StandardError
      nil
    end

    def hobo_session_user
      id = session&.[](:user)
      id && Hobo::Model.find_by_typed_id(id)
    rescue StandardError
      nil
    end

    # An application generated by Hobo has its own `Guest`, and it may want one:
    # a guest with a name, or with a locale. An application that has not defined
    # one gets Hobo's, which says no to everything.
    #
    # The bare `::Guest` that used to be here was resolved by the classic
    # autoloader; in an application without a Guest model it is a NameError, and
    # it happened on *every* request, before any action ran.
    def guest_user
      defined?(::Guest) ? ::Guest.new : Hobo::Model::Guest.new
    end


    # `guest?` is Hobo's own idea: its user model answers it and so does
    # `Hobo::Model::Guest`, which is what stands in for nobody. Piece 15 handed
    # the user to Rails, and **the User that `bin/rails generate authentication`
    # writes has never heard of it** -- so the moment a real person logged in,
    # every request died in a before_action, before any action ran.
    #
    # Nobody saw it until the session was actually being resumed, which is to
    # say: this was hidden behind the bug that made everyone a guest.
    def logged_in?
      user = current_user
      return false if user.nil?
      user.respond_to?(:guest?) ? !user.guest? : true
    end


    def can_create?(object=this)
      if object.is_a?(Class) and object < ActiveRecord::Base
        object = object.new
      elsif (refl = object.try(:proxy_association)&.reflection) && refl.macro == :has_many
        if Hobo.simple_has_many_association?(object)
          new_object = object.build
          new_object.set_creator(current_user)
        else
          return false
        end
      end
      # When running `can_create?(@something.children)`, a new object is instantiated to check if we can create
      # After the check we need to remove it from memory
      if new_object
        new_object.creatable_by?(current_user)
        object.delete(new_object)
      else
        object.creatable_by?(current_user)
      end
    end


    def can_update?(object=this)
      object.updatable_by?(current_user)
    end


    def can_edit?(*args)
      object, field = if args.empty?
                        if !this.respond_to?(:to_a) && this.respond_to?(:editable_by?) && !this_field_reflection
                          [this, nil]
                        elsif this_parent && this_field
                          [this_parent, this_field]
                        else
                          [this, nil]
                        end
                      elsif args.length == 2
                        args
                      else
                        [this, args.first]
                      end

      if !field && (origin = object.try(:origin))
        object, field = origin, object.origin_attribute
      end

      object.editable_by?(current_user, field)
    end


    def can_delete?(object=this)
      object.destroyable_by?(current_user)
    end



    def can_call?(*args)
      method = args.last
      object = args.length == 2 ? args.first : this

      object.method_callable_by?(current_user, method)
    end


    # can_view? has special behaviour if it's passed a class or an
    # association-proxy -- it instantiates the class, or creates a new
    # instance "in" the association, and tests the permission of this
    # object. This means the permission methods in models can't rely
    # on the instance being properly initialised.  But it's important
    # that it works like this because, in the case of an association
    # proxy, we don't want to loose the information that the object
    # belongs_to the proxy owner.
    def can_view?(*args)
      # TODO: Man does this need a big cleanup!

      if args.empty?
        # if we're repeating over an array, this_field ends up with the current index. Is this useful to anybody?
        if this_parent && this_field && !this_field.is_a?(Integer)
          object = this_parent
          field = this_field
        else
          object = this
        end
      elsif args.first.is_one_of?(String, Symbol)
        object = this
        field  = args.first
      else
        object, field = args
      end

      if field
        # Field can be a dot separated path
        if field.is_a?(String) && (path = field.split(".")).length > 1
          _, _, object = Dryml.get_field_path(object, path[0..-2])
          field = path.last
        end
      elsif (origin = object.try(:origin))
        object, field = origin, object.origin_attribute
      end

      @can_view_cache ||= {}
      @can_view_cache[ [object, field] ] ||=
        if !object.respond_to?(:viewable_by?)
          true
        elsif object.viewable_by?(current_user, field)
          # If possible, we also check if the current *value* of the field is viewable
          if field.is_one_of?(Symbol, String) && (v = object.send(field)) && v.respond_to?(:viewable_by?)
            if v.is_a?(Array)
              v.new_candidate.viewable_by?(current_user, nil)
            else
              v.viewable_by?(current_user, nil)
            end
          else
            true
          end
        else
          false
        end
    end


    def select_viewable(collection=this)
      collection.select {|x| can_view?(x)}
    end
end
